name: Get Group Chat Statistics

on:
  schedule:
    - cron:  "00 5 * * *"
  workflow_dispatch:
  
jobs:
  get-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Group Chat Statistics script
        env:
          TGCWS_USERNAME: ${{ secrets.USERNAME }}
          TGCWS_PASSWORD: ${{ secrets.PASSWORD }}

        run: npm run start

      - name: Publish Statistics
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Upload statistics"
          add: "."
